import { open, T, txt, has, click, sleep, ok, done } from "./_h.mjs";
const { browser, page } = await open();
ok((await txt(page, "gm-count")) === "3", "starts at 3");
await click(page, "gm-markread"); await sleep(100);
ok((await txt(page, "gm-count")) === "2", "mark read decrements");
ok(await page.$eval(T("gm-subjects"), (e) => e.querySelector(".subj.is-read")?.textContent === "Scripting update"), "newest struck");
await click(page, "gm-newmail"); await sleep(100);
ok((await txt(page, "gm-count")) === "3", "new mail increments");
ok((await txt(page, "gm-subjects")).includes("Beta invite"), "new subject prepended");
await click(page, "gm-newmail"); await click(page, "gm-newmail"); await sleep(100);
ok((await txt(page, "gm-subjects")).includes("more"), "+N more beyond 4");
await click(page, "gm-open"); await sleep(100);
ok(await has(page, "gm-toast"), "open toast shows");
await sleep(2800);
ok(!(await has(page, "gm-toast")), "toast auto-hides");
await click(page, "gm-archive"); await sleep(700);
ok(!(await has(page, "gm-notif")), "archive removes notification");
await click(page, "gm-restore"); await sleep(100);
ok((await has(page, "gm-notif")) && (await txt(page, "gm-count")) === "3", "restore resets");
await click(page, "gm-delete"); await sleep(700);
ok((await page.$eval(".gm__undo", (e) => e.textContent)).includes("Moved to Trash"), "delete shows Trash text");
await click(page, "gm-restore");
for (let i = 0; i < 3; i++) await click(page, "gm-markread");
await sleep(100);
ok((await page.$eval(".gnotif__t strong", (e) => e.textContent)).includes("All read"), "all read message");
await done(browser);
