import puppeteer from "puppeteer-core";
import { BASE, T, sleep, ok } from "./_h.mjs";
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto(BASE + "/", { waitUntil: "networkidle2", timeout: 90000 });
await sleep(1500);
const v = () => page.$eval(T("hv-video"), (e) => ({ src: e.currentSrc, muted: e.muted, paused: e.paused, t: e.currentTime, w: e.videoWidth, preload: e.preload }));
const frame = () => page.$eval(".hv__frame", (e) => e.getBoundingClientRect().toJSON());
const res = await fetch(BASE + "/media/webwatcher-demo.mp4", { headers: { Range: "bytes=0-99" } });
ok(res.status === 206 || res.status === 200, `video served (${res.status})`);
let s = await v();
ok(s.preload === "metadata" && s.src.endsWith("/media/webwatcher-demo.mp4"), "video preloaded (metadata) from the self-hosted mp4");
ok(s.paused && s.t === 0, "before the click the video is paused at 0 (no autoplay)");
ok(await page.$eval(".hv__poster", (e) => getComputedStyle(e).opacity === "1" && e.complete && e.naturalWidth > 0), "poster image is visible");
const f0 = await frame();
ok(f0.right >= 1440 - 2, "frame bleeds to the right edge (right=" + Math.round(f0.right) + ")");
await page.click(T("hv-play"));
await sleep(1500);
s = await v();
ok(!s.muted && !s.paused && s.t > 0, "click: plays in place with sound (t=" + s.t.toFixed(1) + ")");
ok(!(await page.$("dialog")), "no dialog in the DOM");
ok(JSON.stringify(f0) === JSON.stringify(await frame()), "the frame did not move or resize");
ok(await page.$eval(".hv__poster", (e) => getComputedStyle(e).opacity === "0"), "poster faded out");
ok(await page.$eval(".hv__progress", (e) => !!e.offsetHeight), "progress line present");
await page.click(T("hv-pause"));
await sleep(300);
const t1 = (await v()).t;
await sleep(600);
s = await v();
ok(s.paused && Math.abs(s.t - t1) < 0.05, "pause button pauses");
await page.click(T("hv-pause"));
await sleep(500);
ok(!(await v()).paused, "play button resumes");
await page.click(T("hv-mute"));
ok((await v()).muted, "mute works");
await page.click(T("hv-mute"));
ok(!(await v()).muted, "unmute works");
const w = await page.$eval(".hv__win", (e) => e.getBoundingClientRect().toJSON());
await page.mouse.click(w.left + w.width / 2, w.top + w.height / 3);
await sleep(300);
ok((await v()).paused, "click on the video toggles pause");
await page.mouse.click(w.left + w.width / 2, w.top + w.height / 3);
await sleep(300);
ok(!(await v()).paused, "click on the video resumes");
// ended -> poster returns
await page.$eval(T("hv-video"), (e) => { e.currentTime = e.duration - 0.3; });
await sleep(1500);
ok(await page.$eval(".hv__poster", (e) => getComputedStyle(e).opacity === "1") && !!(await page.$(T("hv-play"))), "at the end the poster and play control return");
// text link
await page.click(T("hv-link"));
await sleep(1200);
s = await v();
ok(!s.paused && !s.muted && s.t < 4, "text link starts playback from the top with sound");
// leaving the viewport pauses
await page.evaluate(() => window.scrollTo(0, 3000));
await sleep(800);
ok((await v()).paused, "scrolling away pauses playback");
// mobile
await page.setViewport({ width: 390, height: 844, isMobile: true });
await page.goto(BASE + "/", { waitUntil: "networkidle2", timeout: 90000 });
await sleep(1000);
ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "390: no horizontal overflow");
const mf = await frame();
ok(Math.abs(mf.left - 16) < 1 && Math.abs(mf.right - 374) < 1, "390: frame full width with 16px gutters");
ok(await page.$eval(".hv__play-btn", (e) => e.offsetWidth === 64), "390: play disc is 64px");
await page.click(T("hv-link"));
await sleep(1500);
ok(!(await v()).paused, "390: text link scrolls to the frame and plays");
await browser.close();
process.exit(0);
