import puppeteer from "puppeteer-core";
import { BASE, T, sleep, ok } from "./_h.mjs";
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--autoplay-policy=user-gesture-required"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto(BASE + "/", { waitUntil: "networkidle2", timeout: 90000 });
await sleep(1500);
const v = () => page.$eval(T("hv-video"), (e) => ({ src: e.currentSrc, muted: e.muted, paused: e.paused, t: e.currentTime, w: e.videoWidth, loop: e.loop, ready: e.readyState }));
const frame = () => page.$eval(".hv__frame", (e) => e.getBoundingClientRect().toJSON());
const res = await fetch(BASE + "/media/webwatcher-demo.mp4", { headers: { Range: "bytes=0-99" } });
ok(res.status === 206 || res.status === 200, `video served (${res.status}, ${res.headers.get("content-type")})`);
let s = await v();
ok(s.src.endsWith("/media/webwatcher-demo.mp4") && s.w > 0, "video element streams the self-hosted mp4 (decoded width " + s.w + ")");
ok(s.muted && s.loop, "before the click it is muted and looping");
const f0 = await frame();
const g = f0.left + f0.width / 2;
ok(Math.abs(g - 720) < 40 || f0.left + f0.width <= 1440 - 60, "frame sits inside the layout (right edge " + Math.round(f0.left + f0.width) + " of 1440)");
await page.click(T("hv-play"));
await sleep(1500);
s = await v();
ok(!s.muted && !s.paused, "click: same video plays with sound (muted=" + s.muted + ")");
ok(s.t < 4, "click restarts from the top (t=" + s.t.toFixed(1) + ")");
ok(!(await page.$("dialog")) && !(await page.$("dialog[open]")), "no dialog / modal exists");
const f1 = await frame();
ok(JSON.stringify(f0) === JSON.stringify(f1), "the frame did not move or resize");
ok(await page.$eval(T("hv-pause"), (e) => !!e), "pause control is present on the frame");
await page.click(T("hv-pause"));
await sleep(300);
const t1 = (await v()).t;
await sleep(600);
s = await v();
ok(s.paused && Math.abs(s.t - t1) < 0.05, "pause stops playback");
await page.click(T("hv-pause"));
await sleep(500);
ok(!(await v()).paused, "play resumes");
await page.click(T("hv-mute"));
ok((await v()).muted, "mute control mutes");
await page.click(T("hv-mute"));
ok(!(await v()).muted, "unmute restores sound");
await browser.close();
process.exit(0);
