import puppeteer from "puppeteer-core";
import { BASE, T, sleep, ok } from "./_h.mjs";
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto(BASE + "/", { waitUntil: "networkidle2", timeout: 90000 });
await sleep(1500);
const v = () => page.$eval(T("hv-video"), (e) => ({ src: e.currentSrc, muted: e.muted, paused: e.paused, t: e.currentTime, w: e.videoWidth, preload: e.preload }));
const frame = () => page.$eval(".hv__frame", (e) => e.getBoundingClientRect().toJSON());
const res = await fetch(BASE + "/video/demo.mp4", { headers: { Range: "bytes=0-99" } });
ok(res.status === 206 || res.status === 200, `video served (${res.status})`);
let s = await v();
ok(s.preload === "metadata" && s.src.endsWith("/video/demo.mp4"), "video preloaded (metadata) from the self-hosted mp4");
ok(s.paused && s.t === 0, "before the click the video is paused at 0 (no autoplay)");
ok(await page.$eval(".hv__poster", (e) => getComputedStyle(e).opacity === "1" && e.complete && e.naturalWidth > 0), "poster image is visible");
const f0 = await frame();
const cw = await page.evaluate(() => document.documentElement.getBoundingClientRect().width);
ok(f0.right >= cw - 2 && f0.right <= cw + 0.5, "frame bleeds to the right edge, not past it (right=" + Math.round(f0.right) + " of " + cw + ")");
const wrap = await page.$eval(".hero__media", (e) => e.getBoundingClientRect().right);
ok(wrap <= cw + 0.5, "media column does not extend past the viewport (" + Math.round(wrap) + ")");
const geo = async (label) => {
  const f = await frame();
  const c = await page.$eval(T("hv-play"), (e) => e.getBoundingClientRect().toJSON());
  const inset = label === 390 ? 12 : 16;
  ok(c.right <= f.right - 8 && c.top >= f.top + f.height / 2 && c.bottom <= f.bottom, label + ": play control is inside the bottom-right quadrant");
  ok(c.left >= f.left + f.width * 0.64 - 1 && c.bottom <= f.bottom - 8, label + ": play control sits in the free gradient right of the page window (left " + Math.round(c.left - f.left) + " of " + Math.round(f.width) + ")");
  ok(Math.abs(f.right - c.right - inset) < 1.5 && Math.abs(f.bottom - c.bottom - inset) < 1.5 && Math.round(c.height) === 44, label + ": control inset " + inset + "px from the right and bottom, 44px tall");
};
await geo(1440);
await page.screenshot({ path: process.env.HERO_SHOT_DIR ? process.env.HERO_SHOT_DIR + "/hero-1440.png" : "/dev/null", clip: await page.$eval("#hero", (e) => { const r = e.getBoundingClientRect(); return { x: r.x, y: r.y + scrollY, width: r.width, height: r.height }; }) });
await page.click(T("hv-play"));
await sleep(1500);
s = await v();
ok(!s.muted && !s.paused && s.t > 0, "click: plays in place with sound (t=" + s.t.toFixed(1) + ")");
ok(!(await page.$("dialog")), "no dialog in the DOM");
ok(JSON.stringify(f0) === JSON.stringify(await frame()), "the frame did not move or resize");
ok(await page.$eval(".hv__poster", (e) => getComputedStyle(e).opacity === "0"), "poster faded out");
ok(await page.$eval(".hv__progress", (e) => !!e.offsetHeight), "progress line present");
await page.click(T("hv-pause"));
await sleep(300);
const t1 = (await v()).t;
await sleep(600);
s = await v();
ok(s.paused && Math.abs(s.t - t1) < 0.05, "pause button pauses");
await page.click(T("hv-pause"));
await sleep(500);
ok(!(await v()).paused, "play button resumes");
await page.click(T("hv-mute"));
ok((await v()).muted, "mute works");
await page.click(T("hv-mute"));
ok(!(await v()).muted, "unmute works");
const w = await page.$eval(".hv__win", (e) => e.getBoundingClientRect().toJSON());
await page.mouse.click(w.left + w.width / 2, w.top + w.height / 3);
await sleep(300);
ok((await v()).paused, "click on the video toggles pause");
await page.mouse.click(w.left + w.width / 2, w.top + w.height / 3);
await sleep(300);
ok(!(await v()).paused, "click on the video resumes");
// ended -> poster returns
await page.$eval(T("hv-video"), (e) => { e.currentTime = e.duration - 0.3; });
await sleep(1500);
ok(await page.$eval(".hv__poster", (e) => getComputedStyle(e).opacity === "1") && !!(await page.$(T("hv-play"))), "at the end the poster and play control return");
// text link: hidden at >=1100 (the on-frame control carries the label), visible and working below
ok(await page.$eval(T("hv-link"), (e) => e.offsetParent === null), "1440: the duplicate text link is hidden (on-frame play control is visible)");
await page.setViewport({ width: 1024, height: 800 });
await sleep(400);
ok(await page.$eval(T("hv-link"), (e) => e.offsetParent !== null), "1024: text link is visible");
await page.click(T("hv-link"));
await sleep(1200);
s = await v();
ok(!s.paused && !s.muted && s.t < 4, "1024: text link starts playback from the top with sound");
// leaving the viewport pauses
await page.evaluate(() => window.scrollTo(0, 3000));
await sleep(800);
ok((await v()).paused, "scrolling away pauses playback");
// mobile
await page.setViewport({ width: 390, height: 844, isMobile: true });
await page.goto(BASE + "/", { waitUntil: "networkidle2", timeout: 90000 });
await sleep(1000);
ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "390: no horizontal overflow");
const mf = await frame();
ok(Math.abs(mf.left - 16) < 1 && Math.abs(mf.right - 374) < 1, "390: frame full width with 16px gutters");
await geo(390);
await page.screenshot({ path: process.env.HERO_SHOT_DIR ? process.env.HERO_SHOT_DIR + "/hero-390.png" : "/dev/null", clip: await page.$eval("#hero", (e) => { const r = e.getBoundingClientRect(); return { x: r.x, y: r.y + scrollY, width: r.width, height: r.height }; }) });
await page.click(T("hv-link"));
await sleep(1500);
ok(!(await v()).paused, "390: text link scrolls to the frame and plays");
ok(!!(await page.$eval(T("hv-video"), (e) => e.getAttribute("src"))), "390: src assigned once play was pressed");
await browser.close();
process.exit(0);
